import type { NextPage } from 'next';
import Head from 'next/head';
import Banner from '~components/Banner';
import FabButton from '~components/FabButton';
import Footer from '~components/Footer/Footer';
import Header from '~components/Header/Header';
// import styles from '../styles/Home.module.css';
import { indicadoHeaderLinks, social } from './data';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Leonardo Shlichting</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header links={indicadoHeaderLinks} social={social} />
      <main>
        <Banner />
        <FabButton />
        <Footer />
      </main>
    </>
  );
};

export default Home;
