import type { NextPage } from 'next';
import Head from 'next/head';
import Atuacao from '~components/Atuacao';
import Atividade from '~components/Atividade';
import Banner from '~components/Banner';
import Contato from '~components/Contato';
import FabButton from '~components/FabButton';
import Footer from '~components/Footer/Footer';
import Header from '~components/Header/Header';
import Missao from '~components/Missao';
// import styles from '../styles/Home.module.css';
import { indicadoHeaderLinks, social } from './data';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Leonardo Schlichting</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header links={indicadoHeaderLinks} social={social} />
      <main>
        <Banner />
        {/* <Atividade /> */}
        <Atuacao />
        <Missao />
        <Contato />
        <FabButton />
        <Footer />
      </main>
    </>
  );
};

export default Home;
